### ISSUE TITLE
Can you provide pretrained weights?

### ISSUE THREAD

**Issue by Realdr4g0n** [ziniuwan/maed#2]
Thanks for your implementation.
Can you provide the pretrained weights for this model?

**Comment by zhLawliet** [comment]
Can you provide the model_best.pth.tar, thanks @ziniuwan

**Comment by ziniuwan** [comment]
Hi! I have added the google drive link of the pretrained weights in the README file. Good luck!

**Comment by zhLawliet** [comment]
thanks @ziniuwan , I found that I used this model, and the results were not consistent with your report，such as “PVE”, so on
![image](https://user-images.githubusercontent.com/17424385/158040323-f5f539ae-e91d-4127-910d-9ca423509cdf.png)

CUDA_VISIBLE_DEVICES=0  python  eval.py --cfg configs/config_stage2.yaml --pretrained ./model_data/model_best.pth.tar --eval_set test

**Comment by hdjang** [comment]
Hi @zhLawliet 

When I use the same command line as you used, I got the following errors. How did you solve this?

<img width="727" alt="image" src="https://user-images.githubusercontent.com/28732827/158521884-b35b1969-bc02-4f61-bb8d-55b2b800c484.png">

**Comment by zhLawliet** [comment]
@hdjang  change the view by reshape
rel_joints.reshape(-1, 3, 1).reshape(-1, joints.shape[1], 4, 4)

**Comment by ziniuwan** [comment]
@hdjang This is a version conflict between smplx and PyTorch. We also found the errors during experiments. Modifying all the view() to reshape() wherever the errors indicate in the smplx code as @zhLawliet said could solve the problems.

**Comment by hdjang** [comment]
Thanks for instant replies! @zhLawliet , @ziniuwan
